version: "3"

services:
  node:
    build: .
    container_name: RealSolve
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_HOST: db

      API_HOST: 'node'
      API_PORT: 3000
      NODE_ENV: 'development'
    networks:
      - RealSolve

  db:
    container_name: RealSolve_db
    image: mysql:8.0.23
    platform: linux/x86_64
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - RealSolve

networks:
  RealSolve:
    driver: bridge
